/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class LangModel {
  static createLocal(
    modelName: string,
    progressCallback?: ((arg: CacheProgress) => void) | undefined | null
  ): Promise<LangModel>;
  static createStreamApi(
    spec: APISpecification,
    modelName: string,
    apiKey: string
  ): LangModel;
  run(
    messages: Array<Message>,
    tools?: Array<ToolDesc> | undefined | null
  ): LangModelRunIterator;
}

export declare class LangModelRunIterator {
  [Symbol.asyncIterator](): this;
  next(): Promise<LanguageModelIteratorResult>;
}

export type APISpecification =
  | "ChatCompletion"
  | "OpenAI"
  | "Gemini"
  | "Claude"
  | "Responses"
  | "Grok";

export interface CacheProgress {
  comment: string;
  current: number;
  total: number;
}

export type FinishReason =
  | { type: "stop" }
  | { type: "length" }
  | { type: "tool_call" }
  | { type: "refusal"; reason: string };

export type Grammar =
  | { type: "plain" }
  | { type: "json" }
  | { type: "jsonschema"; schema: string }
  | { type: "regex"; regex: string }
  | { type: "cfg"; cfg: string };

export interface InferenceConfig {
  thinkEffort?: ThinkEffort;
  temperature?: number;
  topP?: number;
  maxTokens?: number;
  grammar?: Grammar;
}

export interface LanguageModelIteratorResult {
  value: MessageOutput;
  done: boolean;
}

export interface Message {
  role: Role;
  contents: Array<Part>;
  id?: string;
  thinking?: string;
  tool_calls?: Array<Part>;
  signature?: string;
}

export interface MessageDelta {
  role?: Role;
  id?: string;
  thinking?: string;
  contents: Array<PartDelta>;
  tool_calls: Array<PartDelta>;
  signature?: string;
}

export interface MessageOutput {
  delta: MessageDelta;
  finish_reason?: FinishReason;
}

export type Part =
  | { type: "text"; text: string }
  | { type: "function"; id?: string; function: PartFunction }
  | { type: "value"; value: any }
  | { type: "image"; image: PartImage };

export type PartDelta =
  | { type: "text"; text: string }
  | { type: "function"; id?: string; function: PartDeltaFunction }
  | { type: "value"; value: any }
  | { type: "null" };

export type PartDeltaFunction =
  | { type: "verbatim"; text: string }
  | { type: "with_string_args"; name: string; arguments: string }
  | { type: "with_parsed_args"; name: string; arguments: any };

export interface PartFunction {
  name: string;
  arguments: any;
}

export type PartImage = {
  type: "binary";
  height: number;
  width: number;
  colorspace: PartImageColorspace;
  data: Buffer;
};

export type PartImageColorspace = "grayscale" | "rgb" | "rgba";

/** The author of a message (or streaming delta) in a chat. */
export type Role =
  /** System instructions and constraints provided to the assistant. */
  | "system"
  /** Content authored by the end user. */
  | "user"
  /** Content authored by the assistant/model. */
  | "assistant"
  /** Outputs produced by external tools/functions */
  | "tool";

export type ThinkEffort = "disable" | "enable" | "low" | "medium" | "high";

export interface ToolDesc {
  name: string;
  description?: string;
  parameters: any;
  returns?: any;
}
