[project]
name = "ailoy-py"
version = "0.0.6"
description = "Python binding for Ailoy runtime APIs"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Brekkylab Inc.", email = "contact@brekkylab.com"}
]
license = "Apache-2.0"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "anyio>=4.9.0",
    "jmespath>=1.0.1",
    "mcp>=1.8.0",
    "numpy>=2.0.2",
    "pillow>=11.2.1",
    "pydantic>=2.11.4",
    "rich>=14.0.0",
    "typer>=0.15.4",
]

[project.scripts]
ailoy = "ailoy.cli.__main__:app"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
    "ruff>=0.11.8",
    "pdoc>=15.0.3",
]

[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
cmake.source-dir = "../.."
build-dir = "./build"
wheel.packages = ["ailoy"]

[tool.scikit-build.cmake.define]
AILOY_WITH_TEST = "OFF"

[tool.pytest.ini_options]
addopts = "--capture=tee-sys --strict-markers"
asyncio_mode = "strict"
markers = [
    "runtime: tests for low-level runtime APIs",
    "agent: tests for high-level agent APIs",
    "agent_local: tests for local agent",
    "agent_openai: tests for OpenAI agent",
    "agent_gemini: tests for Gemini agent",
    "agent_claude: tests for Claude agent",
    "agent_grok: tests for Grok agent",
]
pythonpath = "tests"
testpaths = ["tests"]

[tool.ruff]
lint.select = [
    "E",    # pycodestyle
    "F",    # pyflakes
    "I",    # isort
]
line-length = 120
