export const S = {
  appName: "Ailoy",
  newChat: "새 대화",
  untitled: "새 대화",
  send: "보내기",
  stop: "중지",
  messageInput: "메시지 입력",
  composerPlaceholder: "메시지를 입력하세요. Enter로 보내고 Shift+Enter로 줄을 바꿉니다.",
  model: "모델",
  thinking: "생각 중",
  running: "실행 중",
  interrupted: "중단됨",
  denied: "거부됨",
  toolCall: "도구 호출",
  workspace: "워크스페이스",
  mounts: "연결",
  addMount: "+ 연결",
  connectLocal: "폴더 연결",
  connectNotion: "Notion 연결",
  connectS3: "S3 연결",
  remove: "제거",
  settings: "설정",
  providers: "모델 프로바이더",
  apiKey: "API 키",
  saveKey: "저장",
  clearKey: "지우기",
  defaultModel: "기본 모델",
  maxTokens: "응답 최대 토큰",
  maxTurns: "턴 상한",
  catalogRefresh: "모델 목록 자동 갱신",
  contextUsage: "컨텍스트",
  sessionTokens: "세션 토큰",
  estimatedCost: "추정 비용",
  rateLimit: "분당 잔여",
  resetIn: "리셋",
  degraded: "워크스페이스가 마운트되지 않아 커넥터는 에이전트에게 보이지 않습니다.",
  noKey: "사용할 프로바이더의 API 키를 설정에서 먼저 입력하세요.",
  authFailed: "API 키가 거부되었습니다. 설정에서 키를 확인하세요.",
  readOnly: "읽기 전용",
  rename: "이름 바꾸기",
  delete: "삭제",
  confirmDelete: "이 대화를 삭제할까요?",
  path: "경로 (예: /notion)",
  label: "표시 이름",
  cancel: "취소",
  connect: "연결",
  continueRun: "계속",
  errorPrefix: "오류",
  fileTooLarge: "미리보기는 1 MiB까지만 표시합니다.",
  binaryFile: "텍스트가 아닌 파일입니다.",
  empty: "비어 있음",
  noSession: "왼쪽에서 대화를 고르거나 새 대화를 시작하세요.",
  loadFailed: "대화를 불러오지 못했습니다.",
  arguments: "인자",
  close: "닫기",
  folder: "폴더",
  selectFolder: "폴더 선택",
  notionToken: "Notion 통합 토큰",
  bucket: "버킷",
  region: "리전",
  accessKeyId: "액세스 키 ID",
  secretAccessKey: "시크릿 액세스 키",
  endpoint: "엔드포인트 (선택)",
  keyPrefix: "키 프리픽스 (선택)",
} as const;
