export const S = {
  appName: "Ailoy",
  newChat: "New chat",
  untitled: "New chat",
  send: "Send",
  stop: "Stop",
  messageInput: "Message",
  composerPlaceholder: "Type a message. Enter sends it, Shift+Enter starts a new line.",
  model: "Model",
  thinking: "Thinking",
  running: "Running",
  interrupted: "Interrupted",
  denied: "Denied",
  toolCall: "Tool call",
  toolCalls: "tool calls",
  queued: "queued",
  callsFailed: "failed",
  callsInterrupted: "interrupted",
  workspace: "Workspace",
  artifacts: "Artifacts",
  collapseSidebar: "Hide sidebar",
  expandSidebar: "Show sidebar",
  mounts: "Connected sources",
  addMount: "+ Connect",
  sourceSettings: "Source settings",
  sourceOptions: "Options",
  mountPath: "Mounted at",
  sourceKind: "Type",
  sourceDetail: "Source",
  removeSource: "Remove source",
  removeSourceHint: "The files stay where they are. Only the connection to this workspace goes away.",
  rootDirectory: "Directory",
  rootDirectoryHint: "The folder on this Mac that the workspace shows. The agent reads it and cannot write to it.",
  rootUndetachable: "The workspace always has a root, so this one cannot be removed.",
  noSources: "No connected sources yet.",
  pickFile: "Pick something on the left to open it.",
  showHidden: "Show hidden files",
  hideHidden: "Hide hidden files",
  row: "Row",
  rows: "rows",
  columns: "columns",
  delimiter: "delimiter-separated",
  showMore: "Show more",
  sheets: "Sheets",
  viewerFailed: "This file could not be opened here.",
  loading: "Opening…",
  chats: "Chats",
  connectLocal: "Connect folder",
  connectNotion: "Connect Notion",
  connectS3: "Connect S3",
  remove: "Remove",
  settings: "Settings",
  providers: "Model providers",
  apiKey: "API key",
  saveKey: "Save",
  clearKey: "Clear",
  defaultModel: "Default model",
  maxTokens: "Max response tokens",
  maxTurns: "Turn limit",
  catalogRefresh: "Refresh the model list automatically",
  contextUsage: "Context",
  sessionTokens: "Session tokens",
  estimatedCost: "Estimated cost",
  rateLimit: "Rate limit",
  rlRequests: "Requests",
  rlTokens: "Tokens",
  rlInput: "Input",
  rlOutput: "Output",
  resetIn: "resets in",
  degraded: "The workspace is not mounted, so the agent cannot see your connections.",
  noKey: "Add an API key for the provider you want to use in Settings first.",
  authFailed: "The API key was rejected. Check it in Settings.",
  readOnly: "Read-only",
  rename: "Rename",
  delete: "Delete",
  confirmDelete: "Delete this chat?",
  path: "Path (e.g. /notion)",
  label: "Display name",
  cancel: "Cancel",
  connect: "Connect",
  continueRun: "Continue",
  errorPrefix: "Error",
  fileTooLarge: "Previews stop at 1 MiB.",
  binaryFile: "Not a text file.",
  empty: "Empty",
  noSession: "Pick a chat on the left, or start a new one.",
  loadFailed: "Could not load this chat.",
  arguments: "Arguments",
  close: "Close",
  folder: "Folder",
  selectFolder: "Choose folder",
  notionToken: "Notion integration token",
  bucket: "Bucket",
  region: "Region",
  accessKeyId: "Access key ID",
  secretAccessKey: "Secret access key",
  endpoint: "Endpoint (optional)",
  keyPrefix: "Key prefix (optional)",
  openLogs: "Open logs folder",
  mounted: "Mounted",
  degradedShort: "Degraded",
} as const;
