export const S = {
  appName: "Ailoy",
  newChat: "New chat",
  chats: "Chats",
  context: "Context",
  agent: "Agent",
  artifacts: "Artifacts",
  settings: "Settings",
  greeting: "What can I help you with?",
  starters: [
    "Summarize what's in my context",
    "Find the most recently changed documents",
    "Draft a brief from the files in a folder",
  ],
  composerPlaceholder: "Message Ailoy",
  messageInput: "Message",
  send: "Send",
  stop: "Stop",
  model: "Model",
  chooseModel: "Choose a model",
  collapseSidebar: "Hide sidebar",
  expandSidebar: "Show sidebar",
  rename: "Rename",
  delete: "Delete",
  confirmDelete: "Delete this chat?",
  copy: "Copy",
  copied: "Copied",
  empty: "Empty",
  noSession: "Pick a chat on the left, or start a new one.",
  newContext: "New context",
  contextName: "Name",
  create: "Create",
  cancel: "Cancel",
  files: "Files",
  pickContext: "Pick a context on the left, or make a new one.",
  path: "Path",
  newFolder: "New folder",
  addFolder: "Add folder",
  addFiles: "Add files",
  name: "Name",
  size: "Size",
  modified: "Modified",
  loading: "Loading…",
  emptyFolder: "This folder is empty.",
  dropHint: "Drop files here, or add them from the bar above.",
  dropHere: "Drop to add",
  closeViewer: "Close viewer",
  items: (n: number) => `${n} item${n === 1 ? "" : "s"}`,
  confirmDeleteFile: (name: string) => `Delete “${name}” from this context? This cannot be undone.`,
  pickFile: "Pick something on the left to open it.",
  noArtifacts: "Nothing has been produced yet.",
  modelsPage: "Models",
  appearancePage: "Appearance",
  apiKey: "API key",
  saveKey: "Save",
  keySaved: "Key saved",
  bedrockKey: "Bedrock API key (bearer token)",
  region: "Region",
  noKeyYet: "No key yet",
  appearanceSection: "Theme",
  theme: "Theme",
  themeSystem: "System",
  themeLight: "Light",
  themeDark: "Dark",
  themeHint: "System follows this Mac's appearance, including when it switches at sunset.",
  noKey: "Add an API key for the provider you want to use in Settings first.",
  newAgent: "New agent",
  newAgentName: "New agent",
  copyOf: (name: string) => `${name} copy`,
  untitled: "Untitled",
  defaultBadge: "default",
  pickAgent: "Pick an agent on the left, or make a new one.",
  agentGeneral: "General",
  agentPrompt: "System prompt",
  agentTools: "Tools",
  agentSandbox: "Sandbox",
  agentSpec: "Spec",
  loadingAgents: "Reading the agents…",
  agentsUnreadable: (why: string) => `The agents could not be read — ${why}`,
  retry: "Retry",
  notSaved: (why: string) => `Not saved — ${why}. The next edit tries again.`,
  saving: "Saving…",
  savedAsFiles: "Saved as files in the cache",
  heldInMemory: "Held in memory — nothing is written outside the app",
  confirmDeleteAgent: (name: string) => `Delete the agent “${name}”? This cannot be undone.`,
  lastAgent: "The last agent cannot be deleted",
  makeDefault: "Make default",
  isDefault: "Default agent",
  duplicate: "Duplicate",
  deleteAgent: "Delete agent",
  notConnected: "UI preview — ailoy is not connected yet, so this is a placeholder reply.",
} as const;
