export const S = {
  appName: "Ailoy",
  newChat: "New chat",
  chats: "Chats",
  context: "Context",
  agent: "Agent",
  artifacts: "Artifacts",
  settings: "Settings",
  greeting: "What can I help you with?",
  starters: [
    "Summarize what's in my context",
    "Find the most recently changed documents",
    "Draft a brief from the files in a folder",
  ],
  composerPlaceholder: "Message Ailoy",
  messageInput: "Message",
  send: "Send",
  stop: "Stop",
  model: "Model",
  chooseModel: "Choose a model",
  collapseSidebar: "Hide sidebar",
  expandSidebar: "Show sidebar",
  rename: "Rename",
  delete: "Delete",
  confirmDelete: "Delete this chat?",
  copy: "Copy",
  copied: "Copied",
  empty: "Empty",
  noSession: "Pick a chat on the left, or start a new one.",
  mounts: "Connected sources",
  addMount: "+ Connect",
  pickFile: "Pick something on the left to open it.",
  noArtifacts: "Nothing has been produced yet.",
  modelsPage: "Models",
  appearancePage: "Appearance",
  apiKey: "API key",
  saveKey: "Save",
  keySaved: "Key saved",
  bedrockKey: "Bedrock API key (bearer token)",
  region: "Region",
  noKeyYet: "No key yet",
  appearanceSection: "Theme",
  theme: "Theme",
  themeSystem: "System",
  themeLight: "Light",
  themeDark: "Dark",
  themeHint: "System follows this Mac's appearance, including when it switches at sunset.",
  noKey: "Add an API key for the provider you want to use in Settings first.",
  notConnected: "UI preview — ailoy is not connected yet, so this is a placeholder reply.",
} as const;
