from collections.abc import Awaitable, Callable
from os import PathLike
from types import TracebackType
from typing import Any, Generic, Self, TypeVar

from .types import (
    AgentSpec,
    LangModelAPISchema,
    Message,
    MessageDeltaOutput,
    MessageOutput,
    ToolDesc,
    Value,
    WebSearchEngine,
)

_Path = str | PathLike[str]
_Content = bytes | str
_T = TypeVar("_T")

# ---- cortex, built in: see `ailoy.cortex` -------------------------------------------------
ERROR_CODES: dict[str, int]

class CortexError(Exception): ...

class ConsoleRefused(CortexError):
    code: int

class ConsoleBroken(CortexError): ...

class Step:
    @staticmethod
    def run(cmd: str) -> Step: ...
    @staticmethod
    def copy(src: _Path, dst: str) -> Step: ...
    @staticmethod
    def env(key: str, value: str) -> Step: ...
    @staticmethod
    def workdir(dir: str) -> Step: ...

class Image:
    """A base and the steps over it. Every method returns a new ``Image``."""

    def __init__(self, base: str | None = None, steps: list[Step | str] = ...) -> None: ...
    @staticmethod
    def from_dockerfile(content: str) -> Image: ...
    def base(self, base: str) -> Image: ...
    def step(self, step: Step | str) -> Image: ...
    def steps(self, steps: list[Step | str]) -> Image: ...

class Directory:
    """A tree assembled in place. Mounting it with ``HostMount`` takes it."""

    def __init__(self) -> None: ...
    def add_file(self, path: _Path, content: _Content) -> None: ...
    def remove_file(self, path: _Path) -> None: ...
    def mount(self, path: _Path, host_dir: _Path) -> None: ...
    def unmount(self, path: _Path) -> None: ...
    def with_file(self, path: _Path, content: _Content) -> Self: ...
    def with_mount(self, path: _Path, host_dir: _Path) -> Self: ...

class HostMount:
    """A ``Directory`` mounted on this host, for as long as something holds it."""

    def __init__(self, fs: Directory, mountpoint: _Path) -> None: ...
    @property
    def mountpoint(self) -> str: ...

class NetworkAccess:
    def __init__(self, reach: str) -> None: ...
    @staticmethod
    def none() -> NetworkAccess: ...
    @staticmethod
    def host() -> NetworkAccess: ...
    @staticmethod
    def public() -> NetworkAccess: ...
    @staticmethod
    def full() -> NetworkAccess: ...
    def with_host_ports(self, ports: list[int]) -> NetworkAccess: ...
    @property
    def reach(self) -> str: ...
    @property
    def host_ports(self) -> list[int]: ...

class ExecResult:
    code: int
    stdout: bytes
    stderr: bytes
    truncated: bool

class ReadResult:
    data: bytes
    size: int

class ConsoleBuilder:
    """Filled in place and emptied by ``build()``. Every setter returns this builder."""

    def __init__(self) -> None: ...
    def stdio_client(self, cmd: list[str]) -> Self: ...
    def mount(self, mount: HostMount | _Path, at: _Path) -> Self: ...
    def mount_readonly(self, mount: HostMount | _Path, at: _Path) -> Self: ...
    def image(self, image: Image) -> Self: ...
    def snapshot(self, snapshot: bytes) -> Self: ...
    def network(self, network: NetworkAccess) -> Self: ...
    def vcpus(self, vcpus: int) -> Self: ...
    def memory_mib(self, memory_mib: int) -> Self: ...
    def gpu(self, gpu: bool) -> Self: ...
    def gpu_memory_mib(self, gpu_memory_mib: int) -> Self: ...
    def disk_gib(self, disk_gib: int) -> Self: ...
    async def build(self) -> Console: ...

class Console:
    @staticmethod
    def builder() -> ConsoleBuilder: ...
    @property
    def mounts(self) -> list[str]: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def exec(self, cmd: list[str], timeout_ms: int | None = None) -> ExecResult: ...
    async def read(
        self, path: str, offset: int | None = None, len: int | None = None
    ) -> ReadResult: ...
    async def write(self, path: str, data: _Content, offset: int | None = None) -> int: ...
    async def snapshot(self) -> bytes: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...

# ---- ailoy ------------------------------------------------------------------------------

class AiloyError(Exception): ...

class AgentBuilder:
    """Filled in place and emptied by ``build()``. Every setter returns this builder."""

    def __init__(self, model: str) -> None: ...
    def agent_provider(self, name: str) -> Self: ...
    def instruction(self, instruction: str) -> Self: ...
    def tool(self, desc: ToolDesc) -> Self: ...
    def tools(self, descs: list[ToolDesc]) -> Self: ...
    def system_tools(self) -> Self: ...
    def shell_tool(self) -> Self: ...
    def web_search_tool(self, engines: list[WebSearchEngine] | None = None) -> Self: ...
    def web_fetch_tool(self) -> Self: ...
    def subagent(self, spec: AgentSpec) -> Self: ...
    def history(self, history: list[Message]) -> Self: ...
    def console(self, console: Console) -> Self: ...
    def memory(self, memfile: str) -> Self: ...
    def skill(self, dir: str) -> Self: ...
    def context_manager(
        self, max_input_tokens: int | None = None, preserve_recent_turns: int | None = None
    ) -> Self: ...
    def max_tokens(self, max_tokens: int) -> Self: ...
    def temperature(self, temperature: float) -> Self: ...
    def top_p(self, top_p: float) -> Self: ...
    def top_k(self, top_k: int) -> Self: ...
    def response_format(self, schema: dict[str, Value]) -> Self: ...
    async def build(self) -> Agent: ...

class AgentRun(Generic[_T]):
    """One turn, iterated with ``async for``. Nothing runs until it is iterated."""

    def __aiter__(self) -> Self: ...
    async def __anext__(self) -> _T: ...
    async def aclose(self) -> None: ...

class Agent:
    @staticmethod
    async def from_spec(
        spec: AgentSpec,
        *,
        agent_provider: str = "default",
        history: list[Message] | None = None,
        console: Console | None = None,
        memory: str | None = None,
    ) -> Agent: ...
    @property
    def history(self) -> list[Message]: ...
    def run(self, query: str | Message) -> AgentRun[MessageOutput]: ...
    def run_stream(self, query: str | Message) -> AgentRun[MessageDeltaOutput]: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...

def add_lang_model_provider(name: str, *, from_env: bool = False) -> None: ...
def register_lang_model(
    pattern: str,
    schema: LangModelAPISchema,
    url: str,
    api_key: str | None = None,
    *,
    provider: str = "default",
) -> None: ...
def add_tool_provider(name: str, *, builtins: bool = True) -> None: ...
def register_tool(
    desc: ToolDesc, func: Callable[..., Any | Awaitable[Any]], *, provider: str = "default"
) -> ToolDesc: ...
async def register_mcp_stdio(
    prefix: str, command: str, args: list[str] = ..., *, provider: str = "default"
) -> list[ToolDesc]: ...
async def register_mcp_streamable_http(
    prefix: str, url: str, *, provider: str = "default"
) -> list[ToolDesc]: ...
def unregister_mcp(prefix: str, *, provider: str = "default") -> int: ...
async def register_a2a(name: str, url: str, *, provider: str = "default") -> ToolDesc: ...
def add_agent_provider(
    name: str, *, lang_model_provider: str = "default", tool_provider: str = "default"
) -> None: ...
