from collections.abc import Awaitable, Callable
from types import TracebackType
from typing import Any, Generic, Literal, Self, TypeVar

from virtx import ConsoleClient

from .types import (
    AgentSpec,
    LangModelAPISchema,
    Message,
    MessageDeltaOutput,
    MessageOutput,
    ToolDesc,
    Value,
    WebSearchEngine,
)

_T = TypeVar("_T")

class AiloyError(Exception): ...

class AgentBuilder:
    """Filled in place and emptied by ``build()``. Every setter returns this builder."""

    def __init__(self, model: str) -> None: ...
    def agent_provider(self, name: str) -> Self: ...
    def instruction(self, instruction: str) -> Self: ...
    def tool(self, desc: ToolDesc) -> Self: ...
    def tools(self, descs: list[ToolDesc]) -> Self: ...
    def system_tools(self) -> Self: ...
    def shell_tool(self) -> Self: ...
    def web_search_tool(self, engines: list[WebSearchEngine] | None = None) -> Self: ...
    def web_fetch_tool(self) -> Self: ...
    def subagent(self, spec: AgentSpec) -> Self: ...
    def history(self, history: list[Message]) -> Self: ...
    def console(self, console: ConsoleClient) -> Self: ...
    def memory(self, memfile: str) -> Self: ...
    def skill(self, dir: str) -> Self: ...
    def context_manager(
        self,
        max_input_tokens: int | None = None,
        preserve_recent_turns: int | None = None,
    ) -> Self: ...
    def max_tokens(self, max_tokens: int) -> Self: ...
    def temperature(self, temperature: float) -> Self: ...
    def top_p(self, top_p: float) -> Self: ...
    def top_k(self, top_k: int) -> Self: ...
    def reasoning(self, effort: Literal["low", "medium", "high"]) -> Self: ...
    def response_format(self, schema: dict[str, Value]) -> Self: ...
    async def build(self) -> Agent: ...

class AgentRun(Generic[_T]):
    """One turn, iterated with ``async for``. Nothing runs until it is iterated."""

    def __aiter__(self) -> Self: ...
    async def __anext__(self) -> _T: ...
    async def aclose(self) -> None: ...

class Agent:
    @staticmethod
    async def from_spec(
        spec: AgentSpec,
        *,
        agent_provider: str = "default",
        history: list[Message] | None = None,
        console: ConsoleClient | None = None,
        memory: str | None = None,
    ) -> Agent: ...
    @property
    def history(self) -> list[Message]: ...
    def run(self, query: str | Message) -> AgentRun[MessageOutput]: ...
    def run_stream(self, query: str | Message) -> AgentRun[MessageDeltaOutput]: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...

def add_lang_model_provider(name: str, *, from_env: bool = False) -> None: ...
def register_lang_model(
    pattern: str,
    schema: LangModelAPISchema,
    url: str,
    api_key: str | None = None,
    *,
    provider: str = "default",
) -> None: ...
def add_tool_provider(name: str, *, builtins: bool = True) -> None: ...
def register_tool(
    desc: ToolDesc,
    func: Callable[..., Any | Awaitable[Any]],
    *,
    provider: str = "default",
) -> ToolDesc: ...
async def register_mcp_stdio(
    prefix: str, command: str, args: list[str] = ..., *, provider: str = "default"
) -> list[ToolDesc]: ...
async def register_mcp_streamable_http(
    prefix: str, url: str, *, provider: str = "default"
) -> list[ToolDesc]: ...
def unregister_mcp(prefix: str, *, provider: str = "default") -> int: ...
async def register_a2a(
    name: str, url: str, *, provider: str = "default"
) -> ToolDesc: ...
def add_agent_provider(
    name: str, *, lang_model_provider: str = "default", tool_provider: str = "default"
) -> None: ...
