//! Model metadata — context window, output cap, prices, capabilities — from models.dev.
//!
//! A snapshot filtered to the providers ailoy speaks is embedded at build time
//! (`assets/models.json`, regenerated by the `gen-catalog` binary); at runtime the same
//! filter runs over a fresh `https://models.dev/api.json` and the result is cached under the
//! app's data directory. A failed refresh leaves the embedded snapshot in place.

use std::{collections::BTreeMap, path::Path, sync::RwLock};

use serde::{Deserialize, Serialize};

use crate::types::ModelCost;

pub const MODELS_DEV_URL: &str = "https://models.dev/api.json";

/// ailoy model-id prefix → models.dev provider id.
pub const PROVIDER_MAP: &[(&str, &str)] = &[
    ("anthropic", "anthropic"),
    ("openai", "openai"),
    ("google", "google"),
    ("x-ai", "xai"),
    ("deepseek", "deepseek"),
    ("moonshotai", "moonshotai"),
    ("bedrock", "amazon-bedrock"),
];

pub fn models_dev_provider(ailoy_prefix: &str) -> Option<&'static str> {
    PROVIDER_MAP
        .iter()
        .find(|(p, _)| *p == ailoy_prefix)
        .map(|(_, id)| *id)
}

/// `"anthropic/claude-opus-5"` → `("anthropic", "claude-opus-5")`.
pub fn split_model_id(ailoy_model: &str) -> Option<(&str, &str)> {
    ailoy_model
        .split_once('/')
        .filter(|(p, m)| !p.is_empty() && !m.is_empty())
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CatalogModel {
    pub id: String,
    pub name: String,
    #[serde(default)]
    pub reasoning: bool,
    #[serde(default)]
    pub tool_call: bool,
    pub context: Option<u64>,
    pub output: Option<u64>,
    pub cost: Option<ModelCost>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CatalogProvider {
    pub name: String,
    pub models: BTreeMap<String, CatalogModel>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CatalogData {
    pub providers: BTreeMap<String, CatalogProvider>,
}

/// The raw models.dev shape, only the fields read here. Everything is optional so a new
/// field upstream never breaks the parse.
#[derive(Deserialize)]
struct RawProvider {
    #[serde(default)]
    name: String,
    #[serde(default)]
    models: BTreeMap<String, RawModel>,
}

#[derive(Deserialize, Default)]
struct RawModel {
    #[serde(default)]
    id: String,
    #[serde(default)]
    name: String,
    #[serde(default)]
    reasoning: bool,
    #[serde(default)]
    tool_call: bool,
    #[serde(default)]
    modalities: RawModalities,
    #[serde(default)]
    limit: RawLimit,
    cost: Option<ModelCost>,
}

#[derive(Deserialize, Default)]
struct RawModalities {
    #[serde(default)]
    output: Vec<String>,
}

#[derive(Deserialize, Default)]
struct RawLimit {
    context: Option<u64>,
    output: Option<u64>,
}

/// Keep the providers ailoy can call and the models an agent can drive: tool-calling, text
/// out, a known context window.
pub fn filter_models_dev(full: &serde_json::Value) -> CatalogData {
    let mut data = CatalogData::default();
    for (_, md_id) in PROVIDER_MAP {
        let Some(raw) = full.get(*md_id) else {
            continue;
        };
        let Ok(provider) = serde_json::from_value::<RawProvider>(raw.clone()) else {
            continue;
        };
        let models: BTreeMap<String, CatalogModel> = provider
            .models
            .into_iter()
            .filter(|(_, m)| {
                m.tool_call
                    && m.modalities.output.iter().any(|o| o == "text")
                    && m.limit.context.is_some()
            })
            .map(|(key, m)| {
                let id = if m.id.is_empty() { key.clone() } else { m.id };
                let name = if m.name.is_empty() {
                    id.clone()
                } else {
                    m.name
                };
                (
                    key,
                    CatalogModel {
                        id,
                        name,
                        reasoning: m.reasoning,
                        tool_call: m.tool_call,
                        context: m.limit.context,
                        output: m.limit.output,
                        cost: m.cost,
                    },
                )
            })
            .collect();
        if !models.is_empty() {
            data.providers.insert(
                md_id.to_string(),
                CatalogProvider {
                    name: provider.name,
                    models,
                },
            );
        }
    }
    data
}

pub struct Catalog {
    data: RwLock<CatalogData>,
}

impl Catalog {
    pub fn from_data(data: CatalogData) -> Catalog {
        Catalog {
            data: RwLock::new(data),
        }
    }

    /// The embedded snapshot, replaced by `cache` when it exists and parses.
    pub fn load(cache: Option<&Path>) -> Catalog {
        let embedded: CatalogData = serde_json::from_str(include_str!("../assets/models.json"))
            .expect("the embedded catalog is generated by gen-catalog and must parse");
        let data = cache
            .and_then(|p| std::fs::read_to_string(p).ok())
            .and_then(|s| serde_json::from_str::<CatalogData>(&s).ok())
            .filter(|d| !d.providers.is_empty())
            .unwrap_or(embedded);
        Catalog::from_data(data)
    }

    pub fn lookup(&self, ailoy_model: &str) -> Option<CatalogModel> {
        let (prefix, model) = split_model_id(ailoy_model)?;
        let md = models_dev_provider(prefix)?;
        self.data
            .read()
            .ok()?
            .providers
            .get(md)?
            .models
            .get(model)
            .cloned()
    }

    pub fn models_for(&self, ailoy_prefix: &str) -> Vec<CatalogModel> {
        let Some(md) = models_dev_provider(ailoy_prefix) else {
            return vec![];
        };
        self.data
            .read()
            .ok()
            .and_then(|d| {
                d.providers
                    .get(md)
                    .map(|p| p.models.values().cloned().collect())
            })
            .unwrap_or_default()
    }

    pub async fn refresh(&self, cache: &Path) -> anyhow::Result<()> {
        let full: serde_json::Value = reqwest::Client::new()
            .get(MODELS_DEV_URL)
            .timeout(std::time::Duration::from_secs(20))
            .send()
            .await?
            .error_for_status()?
            .json()
            .await?;
        let data = filter_models_dev(&full);
        anyhow::ensure!(
            !data.providers.is_empty(),
            "models.dev answered with none of our providers"
        );
        if let Some(parent) = cache.parent() {
            tokio::fs::create_dir_all(parent).await?;
        }
        tokio::fs::write(cache, serde_json::to_vec_pretty(&data)?).await?;
        *self
            .data
            .write()
            .map_err(|_| anyhow::anyhow!("catalog lock poisoned"))? = data;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> serde_json::Value {
        serde_json::json!({
            "anthropic": { "id": "anthropic", "name": "Anthropic", "models": {
                "claude-opus-5": { "id": "claude-opus-5", "name": "Claude Opus 5", "reasoning": true, "tool_call": true,
                    "modalities": {"input": ["text","image"], "output": ["text"]},
                    "limit": {"context": 1000000, "output": 128000},
                    "cost": {"input": 5, "output": 25, "cache_read": 0.5, "cache_write": 6.25} },
                "claude-3-embed": { "id": "claude-3-embed", "name": "Embed", "tool_call": false,
                    "modalities": {"input": ["text"], "output": ["embedding"]}, "limit": {"context": 8000} }
            }},
            "xai": { "id": "xai", "name": "xAI", "models": {
                "grok-4.6": { "id": "grok-4.6", "name": "Grok 4.6", "tool_call": true,
                    "modalities": {"input": ["text"], "output": ["text"]}, "limit": {"context": 256000, "output": 32000}, "cost": {"input": 3, "output": 15} }
            }},
            "someone-else": { "id": "someone-else", "name": "X", "models": {
                "m": { "id": "m", "name": "m", "tool_call": true, "modalities": {"input":["text"],"output":["text"]}, "limit": {"context": 1} }
            }}
        })
    }

    #[test]
    fn filter_keeps_mapped_providers_and_chat_tool_models_only() {
        let data = filter_models_dev(&sample());
        assert!(data.providers.contains_key("anthropic"));
        assert!(data.providers.contains_key("xai"));
        assert!(!data.providers.contains_key("someone-else"));
        let a = &data.providers["anthropic"];
        assert_eq!(a.name, "Anthropic");
        assert!(a.models.contains_key("claude-opus-5"));
        assert!(
            !a.models.contains_key("claude-3-embed"),
            "no tool_call / non-text output"
        );
        let m = &a.models["claude-opus-5"];
        assert_eq!(m.context, Some(1_000_000));
        assert_eq!(m.cost.as_ref().unwrap().cache_write, Some(6.25));
    }

    #[test]
    fn lookup_maps_ailoy_ids_to_models_dev_providers() {
        let cat = Catalog::from_data(filter_models_dev(&sample()));
        assert_eq!(
            cat.lookup("anthropic/claude-opus-5").unwrap().name,
            "Claude Opus 5"
        );
        assert_eq!(cat.lookup("x-ai/grok-4.6").unwrap().context, Some(256_000));
        assert!(cat.lookup("google/gemini-2.5-pro").is_none());
        assert!(cat.lookup("no-slash").is_none());
        assert_eq!(cat.models_for("anthropic").len(), 1);
        assert_eq!(
            split_model_id("bedrock/anthropic.claude-opus-5"),
            Some(("bedrock", "anthropic.claude-opus-5"))
        );
        assert_eq!(models_dev_provider("bedrock"), Some("amazon-bedrock"));
    }

    #[test]
    fn embedded_snapshot_parses_and_has_anthropic() {
        let cat = Catalog::load(None);
        assert!(
            cat.lookup("anthropic/claude-opus-5").is_some(),
            "regenerate assets/models.json with `cargo run -p ailoy-desktop-core --bin gen-catalog`"
        );
    }
}
