name: Build macOS Wheel and Upload to S3

on:
  push:

jobs:
  build-and-upload:
    runs-on: macos-14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install libomp
        run: brew install libomp

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: Build wheel
        working-directory: ${{ github.workspace }}/bindings/python
        run: cibuildwheel
        env:
          MACOSX_DEPLOYMENT_TARGET: "14.0"
          CMAKE_OSX_DEPLOYMENT_TARGET: "14.0"
          OpenMP_ROOT: /opt/homebrew/opt/libomp

      - name: Upload to S3
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp ${{ github.workspace }}/bindings/python/wheelhouse/*.whl s3://${{ env.AWS_S3_BUCKET }}/wheels/
