name: Build Linux Wheels

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build for Python ${{ matrix.python }}
    runs-on: ubuntu-latest

    container:
      image: quay.io/pypa/manylinux_2_28_x86_64

    strategy:
      matrix:
        python: ["cp310-cp310", "cp311-cp311", "cp312-cp312", "cp313-cp313"]

    env:
      PYTHON_BIN: /opt/python/${{ matrix.python }}/bin

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Python build dependencies
        run: |
          $PYTHON_BIN/pip install -U pip
          $PYTHON_BIN/pip install build scikit-build-core

      - name: Install OpenSSL 3.0.16
        run: |
          curl -LO https://www.openssl.org/source/openssl-3.0.16.tar.gz
          tar -xzf openssl-3.0.16.tar.gz
          cd openssl-3.0.16
          ./config --prefix=/opt/openssl --openssldir=/opt/openssl no-shared
          make -j$(nproc)
          make install_sw

      - name: Install Vulkan SDK
        run: |
          curl -LO https://sdk.lunarg.com/sdk/download/latest/linux/vulkan-sdk.tar.xz
          mkdir -p /opt/vulkan-sdk
          tar -xJf vulkan-sdk.tar.xz --strip-components=1 -C /opt/vulkan-sdk

      - name: Build wheel
        working-directory: bindings/python
        run: |
          $PYTHON_BIN/python -m build --wheel --outdir /tmp/dist
        env:
          OPENSSL_ROOT_DIR: /opt/openssl
          VULKAN_SDK: /opt/vulkan-sdk/x86_64
          LD_LIBRARY_PATH: /opt/openssl/lib:/opt/vulkan-sdk/x86_64/lib
          PATH: /opt/vulkan-sdk/x86_64/bin:$PATH

      - name: Auditwheel repair
        run: |
          mkdir -p /tmp/wheelhouse
          auditwheel repair /tmp/dist/*.whl --plat manylinux2014_x86_64 -w /tmp/wheelhouse
          auditwheel show /tmp/wheelhouse/*.whl
