name: Build macOS Wheel and Upload to S3

on:
  push:

jobs:
  build-and-upload:
    runs-on: macos-14

    env:
      MACOSX_DEPLOYMENT_TARGET: "11.0"
      CMAKE_OSX_DEPLOYMENT_TARGET: "11.0"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      
      - name: Install libomp
        run: brew install libomp

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build wheel
        working-directory: ${{ github.workspace }}/bindings/python
        run: python -m build

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --exact-timestamps
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: ${{ github.workspace }}/bindings/python/dist
          DEST_DIR: 'wheels/'
