name: Build macOS Wheel and Upload to S3

on:
  push:

jobs:
  build-and-upload:
    runs-on: macos-14

    env:
      MACOSX_DEPLOYMENT_TARGET: "14.0"
      CMAKE_OSX_DEPLOYMENT_TARGET: "14.0"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install libomp
        run: brew install libomp

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: Build ailoy core
        run: |
          cmake --preset apple-clang-release -DAILOY_WITH_TEST=OFF
          cmake --build ${{ github.workspace }}/build/apple-clang-release --parallel $(sysctl -n hw.logicalcpu)
          cmake --install ${{ github.workspace }}/build/apple-clang-release
        env:
          OpenMP_ROOT: /opt/homebrew/opt/libomp

      - name: Build wheels
        working-directory: ${{ github.workspace }}/bindings/python
        run: cibuildwheel

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: macos-wheels
          path: ${{ github.workspace }}/bindings/python/wheelhouse/*.whl
