name: Build and Deploy Document

on:
  release:
    types: released

defaults:
  run:
    working-directory: docs

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: "**/package-lock.json"

      - name: Build Typescript API Document
        run: npx typedoc ../bindings/js-node/src/index.ts --tsconfig ../bindings/js-node/tsconfig.json --favicon static/img/favicon.ico --out static/tsdocs

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip

      - name: Install ailoy-python
        run: pip install ../bindings/python

      - name: Install pdoc
        run: pip install pdoc

      - name: Build Python API Document
        run: pdoc -o static/pydocs --logo /ailoy/img/logo-letter.png --favicon /ailoy/img/favicon.ico ../bindings/python/ailoy

      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
